import React,{useEffect,useMemo,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {getHistory,updateMe,requestUpgrade,getAccountSources,getAccountStats} from '../api.js';

// Real trend line built from the user's own report history (getAccountStats) —
// not a decorative squiggle. Renders nothing until there's at least 2 points.
function Sparkline({points}){
 if(!points||points.length<2)return <div className="muted" style={{fontSize:11.5,padding:'18px 0'}}>Not enough runs yet to chart a trend — this fills in as you verify more content.</div>;
 const w=320,h=56,pad=4;
 const max=100,min=0;
 const step=(w-pad*2)/(points.length-1);
 const xy=points.map((p,i)=>[pad+i*step, h-pad-((p.trustScore??0)-min)/(max-min)*(h-pad*2)]);
 const path=xy.map((p,i)=>(i===0?'M':'L')+p[0].toFixed(1)+','+p[1].toFixed(1)).join(' ');
 const last=xy[xy.length-1];
 return <svg className="sparkline" viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none">
  <path d={path} fill="none" stroke="#D97757" strokeWidth="2"/>
  <circle cx={last[0]} cy={last[1]} r="3" fill="#D97757"/>
 </svg>;
}

function Donut({counts}){
 const entries=Object.entries(counts||{}).filter(([,v])=>v>0);
 const total=entries.reduce((a,[,v])=>a+v,0);
 const colors={'Likely Real':'#3E7A55','Likely Fake':'#B23F35',Unclear:'#B98520'};
 if(total===0)return <div className="muted" style={{fontSize:11.5}}>No verification runs yet.</div>;
 let acc=0;
 const r=30,c=2*Math.PI*r;
 return <div style={{display:'flex',gap:16,alignItems:'center'}}>
  <svg width="72" height="72" viewBox="0 0 72 72">
   <circle cx="36" cy="36" r={r} fill="none" stroke="#E7E2D9" strokeWidth="10"/>
   {entries.map(([k,v],i)=>{const frac=v/total;const dash=frac*c;const el=<circle key={k} cx="36" cy="36" r={r} fill="none" stroke={colors[k]||'#7386A8'} strokeWidth="10" strokeDasharray={`${dash} ${c-dash}`} strokeDashoffset={-acc} transform="rotate(-90 36 36)"/>;acc+=dash;return el;})}
  </svg>
  <div className="donut-legend">{entries.map(([k,v])=><span key={k}><i style={{background:colors[k]||'#7386A8'}}/>{k}: {v}</span>)}</div>
 </div>;
}
const plans=[
 {name:'Free',price:0,annual:0,limit:'50',seats:1,desc:'Try DeepTrust on a handful of items a month.',features:['50 verifications a month','1 seat','Text, article and video verification','PDF report export','Community support']},
 {name:'Starter',price:4000,annual:40000,limit:'100',seats:1,desc:'One person checking a handful of items a day.',features:['100 verifications a month','1 seat','Image forensics + PDF export','6-month report retention','Email support']},
 {name:'Team',price:24000,annual:240000,limit:'500',seats:5,desc:'A small desk sharing one source list.',features:['500 verifications a month','5 seats','Full video & audio forensics','Your own source rankings','Custom scoring weights']},
 {name:'Newsroom',price:68000,annual:680000,limit:'2,000',seats:20,desc:'A full newsroom with several beats running at once.',features:['2,000 verifications a month','20 seats','10 live news beats','Per-desk scoring weights','Priority support · 4 hours'],chosen:true},
];
function Header({eyebrow,title,sub,action}){return <div className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{sub}</p></div>{action}</div>}
function Table({rows,nav}){return <div className="table-card">{rows.length===0?<div className="empty">No verification runs match this view.</div>:<table><thead><tr><th>CONTENT</th><th>TYPE</th><th>VERDICT</th><th>TRUST</th><th>DATE</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} onClick={()=>nav('/results/'+r.id)}><td className="content-cell">{r.inputRef}</td><td><span className="mono">{r.inputType}</span></td><td><span className={'status '+(r.verdict==='Likely Real'?'real':r.verdict==='Likely Fake'?'fake':'unclear')}>{r.verdict||'Unclear'}</span></td><td className="score">{r.trustScore}%</td><td className="muted">{new Date(r.createdAt).toLocaleString()}</td></tr>)}</tbody></table>}</div>}

export function LatestNews(){const nav=useNavigate();const [rows,setRows]=useState([]);useEffect(()=>{getHistory().then(x=>setRows(x.data.reports||[])).catch(()=>{})},[]);return <div className="page maxw"><Header eyebrow="LATEST NEWS" title="Latest news" sub="Every verification you've run, scored on arrival." action={<button className="btn btn-ghost" onClick={()=>nav('/analyze/newsUrl')}>Run a check</button>}/><div className="notice" style={{marginBottom:12}}><b>Evidence-first feed:</b> This view shows verification history from your account. Use New DeepTrust to verify a link, video, image, PDF or text.</div><Table rows={rows} nav={nav}/></div>}
export function FakeDesk(){const nav=useNavigate();const [rows,setRows]=useState([]);useEffect(()=>{getHistory().then(x=>setRows((x.data.reports||[]).filter(r=>r.verdict==='Likely Fake'))).catch(()=>{})},[]);return <div className="page maxw"><Header eyebrow="FAKE NEWS DESK" title="Fake news" sub="Scored below the configured threshold, grouped for review. Open any run to inspect claims, sources and media evidence." action={<button className="btn btn-clay" onClick={()=>nav('/analyze/newsUrl')}>Run a check</button>}/><div className="notice" style={{marginBottom:12}}><b>Review rule:</b> A low trust score is a review signal, not proof by itself. Confirm the evidence trail before publishing.</div><Table rows={rows} nav={nav}/></div>}

export function Settings({user,refreshUser}){
 const [tab,setTab]=useState('profile');
 const [liveSources,setLiveSources]=useState(null);
 useEffect(()=>{if(tab==='sources'&&!liveSources)getAccountSources().then(r=>setLiveSources(r.data)).catch(()=>setLiveSources({sources:[],categories:{}}))},[tab,liveSources]);
 const [profile,setProfile]=useState({name:'',mobile:'',company:'',website:'',role:'',beats:'',notifyBelow:true,notifyDigest:false,notifyRanking:false});
 const [saving,setSaving]=useState(false);const [saved,setSaved]=useState(false);
 useEffect(()=>{if(user)setProfile({name:user.name||'',mobile:user.mobile||'',company:user.company||'',website:user.website||'',role:user.role||'',beats:user.beats||'',notifyBelow:user.notifyBelow!==false,notifyDigest:!!user.notifyDigest,notifyRanking:!!user.notifyRanking})},[user]);
 const [weights,setWeights]=useState(()=>JSON.parse(localStorage.getItem('dt_weights')||'null')||{source:25,evidence:35,claims:25,visual:15});
 const [thresholds,setThresholds]=useState(()=>JSON.parse(localStorage.getItem('dt_thresholds')||'null')||{fake:40,real:75,docPenalty:4,mediaPenalty:3});
 const saveProfile=async()=>{setSaving(true);setSaved(false);try{await updateMe(profile);refreshUser&&refreshUser();setSaved(true);setTimeout(()=>setSaved(false),2500);}catch(e){alert(e.response?.data?.error||'Could not save your profile. Please try again.')}finally{setSaving(false)}};
 const saveAlgo=()=>{localStorage.setItem('dt_weights',JSON.stringify(weights));localStorage.setItem('dt_thresholds',JSON.stringify(thresholds));alert('Scoring algorithm saved. New verifications will use these weights and thresholds.')};
 const total=Object.values(weights).reduce((a,b)=>a+Number(b),0);
 const updateWeight=(key,val)=>{const others=Object.entries(weights).filter(([k])=>k!==key).reduce((a,[,v])=>a+Number(v),0);setWeights(w=>({...w,[key]:Math.max(0,Math.min(100-total+Number(w[key]),Number(val)))}));};
 const limit=user?.planLimit;const used=user?.usedThisCycle||0;
 return <div className="page maxw">
 <Header eyebrow="WORKSPACE SETTINGS" title="Settings" sub="Your profile, source rankings and scoring algorithm."/>
 <div className="set-tabs">{['profile','sources','algo'].map(t=><button key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t==='profile'?'Profile':t==='sources'?'Sources':'Scoring algorithm'}</button>)}</div>
 {tab==='profile'&&<div className="settings-split"><div className="card pad"><div className="profile-head"><span className="profile-avatar">{(profile.name||user?.email||'?').slice(0,2).toUpperCase()}</span><div><b>{profile.name||user?.email}</b><span>{profile.role||'—'}{profile.company?` · ${profile.company}`:''}</span></div></div><div className="two"><Field label="Full name" value={profile.name} onChange={v=>setProfile({...profile,name:v})}/><Field label="Work email" value={user?.email||''} onChange={()=>{}} disabled/><Field label="Mobile" value={profile.mobile} onChange={v=>setProfile({...profile,mobile:v})}/><Field label="Company" value={profile.company} onChange={v=>setProfile({...profile,company:v})}/><Field label="Website" value={profile.website} onChange={v=>setProfile({...profile,website:v})}/><Field label="Role" value={profile.role} onChange={v=>setProfile({...profile,role:v})}/></div><Field label="Beats you follow" value={profile.beats} onChange={v=>setProfile({...profile,beats:v})}/><div className="hr" style={{margin:'6px 0 16px'}}/><div className="eyebrow" style={{marginBottom:10}}>ALERTS</div><div className="stack g10" style={{marginBottom:18}}><Check checked={profile.notifyBelow} onChange={v=>setProfile({...profile,notifyBelow:v})}>Flag anything I verify that scores below 40</Check><Check checked={profile.notifyDigest} onChange={v=>setProfile({...profile,notifyDigest:v})}>Daily digest of my flagged verifications</Check><Check checked={profile.notifyRanking} onChange={v=>setProfile({...profile,notifyRanking:v})}>Notify me when a source's ranking changes</Check></div><button className="btn btn-clay" onClick={saveProfile} disabled={saving}>{saving?'Saving…':'Save changes'}</button>{saved&&<span className="muted" style={{marginLeft:12}}>Saved.</span>}</div><div className="card mini"><div className="mini-t">Workspace</div><KV k="Plan" v={user?.plan||'Free'}/><KV k="Verifications" v={`${used}${limit?` / ${limit}`:''}`}/><KV k="Member since" v={user?.createdAt?new Date(user.createdAt).toLocaleDateString():'—'}/></div></div>}
 {tab==='sources'&&<div><div className="between wrap" style={{marginBottom:14}}><p className="muted" style={{maxWidth:'52em',fontSize:13.5}}>This is the live reputation table the Fact Verification agent actually looks hostnames up against (0–10 score) — not a curated demo list. It updates the moment the backend table changes.</p></div>{!liveSources?<div className="card pad muted">Loading live source table…</div>:<div className="source-table-live">{Object.entries(liveSources.categories||{}).sort((a,b)=>b[1]-a[1]).map(([cat,count])=><div key={cat}><div className="source-cat-head">{cat.replace(/-/g,' ')} · {count}</div><table><tbody>{liveSources.sources.filter(x=>x.category===cat).map(x=><tr key={x.hostname}><td style={{width:'55%'}}>{x.hostname}</td><td className="mono">SCORE {x.score}</td></tr>)}</tbody></table></div>)}</div>}<p className="help">{liveSources?`${liveSources.total} hostnames scored · pulled live from the pipeline's reputation table.`:''}</p></div>}
 {tab==='algo'&&<div className="settings-split"><div><div className="card pad" style={{marginBottom:14}}><div className="between"><h3>Factor weights</h3><span className="mono">Total {total}%</span></div><p className="muted" style={{fontSize:13,margin:'8px 0 10px'}}>Weights must total 100. The report policy uses source authority, evidence quality, claim confidence and visual/media signals.</p><div className="weight-grid">{Object.entries(weights).map(([k,v])=><label key={k}><span>{k}</span><input type="range" min="0" max="100" value={v} onChange={e=>updateWeight(k,e.target.value)}/><b>{v}%</b></label>)}</div>{total!==100&&<div className="warnbox">Weights total <b>{total}%</b>. Bring them back to 100 to save.</div>}<div className="row g8" style={{marginTop:16}}><button className="btn btn-clay" onClick={saveAlgo} disabled={total!==100}>Save algorithm</button><button className="btn btn-ghost" onClick={()=>setWeights({source:25,evidence:35,claims:25,visual:15})}>Reset to DeepTrust default</button></div></div><div className="card pad"><h3 style={{marginBottom:10}}>Thresholds and penalties</h3><Slider label="Fake below" note="Anything under this lands on the fake-news desk" value={thresholds.fake} min={10} max={60} onChange={v=>setThresholds({...thresholds,fake:v})}/><Slider label="Real above" note="Cleared for citation without a second read" value={thresholds.real} min={60} max={95} onChange={v=>setThresholds({...thresholds,real:v})}/><Slider label="Fabricated-document penalty" note="Flat deduction when a primary document fails to resolve" value={thresholds.docPenalty} min={0} max={10} onChange={v=>setThresholds({...thresholds,docPenalty:v})} prefix="−"/><Slider label="Media-manipulation penalty" note="Per confirmed edited region, capped at 6" value={thresholds.mediaPenalty} min={0} max={6} onChange={v=>setThresholds({...thresholds,mediaPenalty:v})} prefix="−"/></div></div><div className="card mini"><div className="mini-t">How this is used</div><p className="help">These weights and thresholds are sent with every new verification and genuinely change the computed trust score and verdict — they're not just saved locally.</p></div></div>}
 </div>
}
function Field({label,value,onChange,disabled}){return <label className="field"><span>{label}</span><input className="inp" value={value} disabled={disabled} onChange={e=>onChange(e.target.value)}/></label>}
function Check({checked,onChange,children}){return <label className="check"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/>{children}</label>}
function KV({k,v}){return <div className="kv"><span>{k}</span><b>{v}</b></div>}
function Slider({label,note,value,min,max,onChange,prefix=''}){return <div className="sldrow"><div><div>{label}</div><small>{note}</small></div><input type="range" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))}/><span className="num">{prefix}{value}</span></div>}

export function Account({user}){const nav=useNavigate();const limit=user?.planLimit;const used=user?.usedThisCycle||0;const pct=limit?Math.min(100,Math.round((used/limit)*100)):0;const [stats,setStats]=useState(null);useEffect(()=>{getAccountStats().then(r=>setStats(r.data)).catch(()=>{})},[]);return <div className="page maxw"><Header eyebrow="ACCOUNT" title="My account" sub="Your plan, your usage, and your profile."/><div className="grid3" style={{marginBottom:14}}><div className="card pad"><div className="eyebrow">Plan</div><div className="big-value">{user?.plan||'Free'}</div><p className="muted">{limit?`${limit} verifications / month`:'Unlimited verifications'}</p><button className="btn btn-ghost btn-full" style={{marginTop:12}} onClick={()=>nav('/upgrade')}>Change plan</button></div><div className="card pad"><div className="eyebrow">Verifications this cycle</div><div className="big-value">{used} {limit&&<span className="muted small-value">/ {limit}</span>}</div><div className="usage-bar"><i style={{width:pct+'%'}}/></div><p className="muted">Resets on the 1st of next month</p></div><div className="card pad"><div className="eyebrow">Profile</div><div className="big-value" style={{fontSize:22}}>{user?.name||'—'}</div><p className="muted">{user?.email}</p><button className="btn btn-ghost btn-full" style={{marginTop:12}} onClick={()=>nav('/settings')}>Edit profile</button></div></div><div className="grid3" style={{marginBottom:14}}><div className="card pad" style={{gridColumn:'span 2'}}><div className="eyebrow">Trust score trend</div><p className="muted" style={{fontSize:11.5,margin:'4px 0 6px'}}>Last {stats?.trend?.length||0} verification runs, most recent on the right.</p><Sparkline points={stats?.trend}/></div><div className="card pad"><div className="eyebrow">Verdict mix</div><div style={{marginTop:8}}><Donut counts={stats?.distribution}/></div></div></div><div className="card pad"><div className="between wrap g12"><div><b>Member since</b><p className="muted">{user?.createdAt?new Date(user.createdAt).toLocaleDateString():'—'}</p></div><div><b>Avg. evidence coverage</b><p className="muted">{stats?.avgEvidenceCoverage??0}% of claims across your reports had a source found</p></div><div><b>Sources checked</b><p className="muted">{stats?.totalSourcesChecked??0} sources kept across {stats?.totalReports??0} report(s)</p></div></div></div></div>}

export function Subscription({user}){const nav=useNavigate();const limit=user?.planLimit;const used=user?.usedThisCycle||0;const pct=limit?Math.min(100,Math.round((used/limit)*100)):0;const [stats,setStats]=useState(null);useEffect(()=>{getAccountStats().then(r=>setStats(r.data)).catch(()=>{})},[]);return <div className="page maxw"><Header eyebrow="BILLING" title="My subscription" sub="What you're on and what you've used this cycle." action={<button className="btn btn-clay" onClick={()=>nav('/upgrade')}>Change plan</button>}/><div className="grid3" style={{marginBottom:14}}><div className="card pad"><div className="between"><span className="eyebrow">Current plan</span><span className="status real">Active</span></div><div className="big-value">{user?.plan||'Free'}</div><p className="muted">{limit?`${limit} verifications / month`:'Unlimited verifications'}</p><button className="btn btn-ghost btn-full" style={{marginTop:12}} onClick={()=>nav('/upgrade')}>Compare plans</button></div><div className="card pad"><div className="eyebrow">Verifications used</div><div className="big-value">{used} {limit&&<span className="small-value muted">/ {limit}</span>}</div><div className="usage-bar"><i style={{width:pct+'%'}}/></div><p className="muted">Resets on the 1st · unused verifications don't carry over</p></div><div className="card pad"><div className="eyebrow">Billing</div><p className="muted" style={{marginTop:8}}>No payment method is on file yet. Upgrade requests are logged for our team to set up billing with you directly.</p></div></div><div className="card pad" style={{marginBottom:14}}><div className="eyebrow">Trust score trend</div><p className="muted" style={{fontSize:11.5,margin:'4px 0 6px'}}>Your last {stats?.trend?.length||0} verification runs.</p><Sparkline points={stats?.trend}/></div><div className="card pad"><div className="between wrap g12"><div><b>Need a higher limit or more seats?</b><p className="muted">Send an upgrade request from the plans page — no card required right now.</p></div><button className="btn btn-ghost" onClick={()=>nav('/upgrade')}>View plans</button></div></div></div>}

export function Upgrade({user,refreshUser}){const [cycle,setCycle]=useState('month');const [plan,setPlan]=useState(user?.plan&&plans.some(p=>p.name===user.plan)?user.plan:'Team');const [sent,setSent]=useState(false);const [sending,setSending]=useState(false);const chosen=plans.find(p=>p.name===plan)||plans[2];const used=user?.usedThisCycle||0;const limit=user?.planLimit;
 const send=async()=>{setSending(true);try{await requestUpgrade(plan,cycle);setSent(true)}catch(e){alert(e.response?.data?.error||'Could not send the request. Please try again.')}finally{setSending(false)}};
 return <div className="page maxw upgrade-page"><div className="center-head"><div className="eyebrow">PLANS</div><h1>Choose the plan that fits your desk</h1><p>You're on <b>{user?.plan||'Free'}</b> and have used {used}{limit?` of ${limit}`:''} verifications this cycle.</p></div><div className="cycle"><button className={cycle==='month'?'on':''} onClick={()=>setCycle('month')}>Monthly</button><button className={cycle==='year'?'on':''} onClick={()=>setCycle('year')}>Annual <em>2 MONTHS FREE</em></button></div><div className="plan-grid-full">{plans.map(p=><button key={p.name} className={'plan-card-full '+(plan===p.name?'selected':'')} onClick={()=>{setPlan(p.name);setSent(false)}}><div className="plan-top"><b>{p.name}</b>{p.chosen&&<span>MOST CHOSEN</span>}</div>{user?.plan===p.name&&<small className="your-plan">YOUR PLAN</small>}<p>{p.desc}</p><h2>{p.price===0?'Free':`₹${(cycle==='month'?p.price:p.annual).toLocaleString('en-IN')}`}</h2><small>{p.price===0?'':cycle==='month'?'PER MONTH':'PER YEAR'}</small><ul>{p.features.map(f=><li key={f}>✓ {f}</li>)}</ul><div className="select-plan">{plan===p.name?'Selected':`Select ${p.name}`}</div></button>)}</div><div className="between wrap g16" style={{marginTop:24}}><p className="help" style={{maxWidth:'44em'}}>Prices exclude 18% GST. There's no payment processor connected yet — requesting a plan logs it for our team to follow up and activate manually.</p>{sent?<span className="status real" style={{padding:'10px 16px'}}>Request sent — we'll follow up by email</span>:<button className="btn btn-clay btn-lg" onClick={send} disabled={sending||plan===user?.plan}>{sending?'Sending…':plan===user?.plan?'This is your current plan':`Request ${plan} →`}</button>}</div><CompareTable selected={plan} cycle={cycle} onSelect={setPlan} onCycle={setCycle}/></div>}
function CompareTable({selected,cycle,onSelect,onCycle}){return <div className="card compare-card"><div className="between wrap"><div><h3>Compare plans</h3><p className="muted">The highlighted column is what you've selected. Pick from here or from the cards above — it's the same order.</p></div><button className="btn btn-ghost" onClick={()=>onCycle(cycle==='month'?'year':'month')}>{cycle==='month'?'Show annual pricing':'Show monthly pricing'}</button></div><div style={{overflowX:'auto'}}><table className="compare-table"><thead><tr><th>WHAT YOU GET</th>{plans.map(p=><th className={selected===p.name?'hi':''} key={p.name} onClick={()=>onSelect(p.name)}>{p.name}</th>)}</tr></thead><tbody>{['Verifications / month','Seats','Video & audio forensics','Source rankings','Custom scoring weights'].map((x,i)=><tr key={x}><td>{x}</td>{plans.map(p=><td className={selected===p.name?'hi':''} key={p.name}>{i===0?p.limit:i===1?p.seats:i===2?'✓':i===3?'✓':(p.name==='Free'?'—':'✓')}</td>)}</tr>)}</tbody></table></div></div>}
